changes

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,7 +1,7 @@
-#!/usr/bin/env bash
+#!/usr/bin/env sh
 
 set -o errexit
-set -o pipefail
+#set -o pipefail
 set -o nounset
 
 show_help() 
@@ -73,29 +73,34 @@ while :; do
 		--program-prefix=) ;;
 		--disable-dependency-tracking) DEPS=0 ;;
 		--enable-dependency-tracking) DEPS=1 ;;
-		*) [[ -n "${1-}" ]] && { echo "Unknown argument ${1}" >&2; exit 1; } ;;
+		*) [ -n "${1-}" ] && { echo "Unknown argument ${1}" >&2; exit 1; } ;;
 	esac
-	shift || break
+	shift 2>/dev/null || break
 done
 
 # log all of the scripts output to config.log
-if [[ ${QUIET} == 0 ]]; then
-	exec &> >(tee config.log)
+if [ ${QUIET} = 0 ]; then
+	FIFO="/tmp/$$.pipe"
+	mkfifo "${FIFO}"
+	# shellcheck disable=SC2064
+	trap "{ rm -f ${FIFO}; }" EXIT
+	tee <"${FIFO}" &
+	exec 1>"${FIFO}"
 else
-	exec &>config.log
+	exec 1>config.log
 fi
 
 OBJDIR=$(pwd)
 SRCDIR=$(dirname "${0}")
 
-if [[ "$(realpath "${OBJDIR}")" = "$(realpath "${SRCDIR}")" ]]; then
+if [ "$(realpath "${OBJDIR}")" = "$(realpath "${SRCDIR}")" ]; then
 	echo "Building inside source directory."
 fi
 
 # Default file locations, or use env provided ones
 
 PREFIX=${PREFIX:-/usr/local}
-[[ "${PREFIX}" = "/" ]] &&  PREFIX=""
+[ "${PREFIX}" = "/" ] &&  PREFIX=""
 EXECPREFIX=${EXECPREFIX:-${PREFIX}}
 DATAROOTDIR=${DATAROOTDIR:-${PREFIX}/share}
 BINDIR=${BINDIR:-${EXECPREFIX}/bin}
@@ -117,7 +122,7 @@ LEX=${LEX:-lex}
 LFLAGS=${LFLAGS:-}
 YFLAGS=${YFLAGS:-}
 
-[[ -n "${TARGET}" ]] && TOOL="${TARGET}-" || TOOL=""
+[ -n "${TARGET}" ] && TOOL="${TARGET}-" || TOOL=""
 
 # Default compiler flags
 
@@ -137,18 +142,26 @@ CXX=${CXX:-${TOOL}g++}
 PACKAGE=$(cat "${SRCDIR}/misc/PACKAGE")
 VERSION=$(cat "${SRCDIR}/misc/VERSION")
 
+# Support functions
+
+fail()
+{
+	echo "${1}" >&2
+	exit 1
+}
+
 # Check for a c compiler (mandatory)
 
-echo -n "Checking for a C compiler ... "
-if [[ ! -x "$(which "${CC}")" ]]; then
-	fail "Error: CC not valid"
-else
+printf "Checking for a C compiler ... "
+if env -i "PATH=$PATH" command -v "${CC}" >/dev/null 2>&1; then
 	export CC
-	which "${CC}" | tee -a config.log
+	env -i "PATH=$PATH" command -v "${CC}"
+else
+	fail "Error: CC not valid"
 fi
 
-echo -n "Checking $(basename "${CC}") can produce executables ... "
-echo -e '#include <stdlib.h>\nmain() {exit(0);}' | \
+printf "Checking %s can produce executables ... " "$(basename "${CC}")"
+printf '#include <stdlib.h>\nmain() {exit(0);}' | \
 	if ${CC} -xc -o /dev/null - 2>>config.log; then
 		echo "Ok"
 	else
@@ -157,8 +170,12 @@ echo -e '#include <stdlib.h>\nmain() {exit(0);}' | \
 
 HOST_MACHINE=$(${CC} -dumpmachine)
 
-echo -n "Configuring ${PACKAGE} ${VERSION} on ${HOST_MACHINE}"
-[[ -n "${TARGET}" ]] &&	echo " for target ${TARGET}" || echo ""
+printf "Configuring %s %s on %s" "${PACKAGE}" "${VERSION}" "${HOST_MACHINE}"
+if [ -n "${TARGET}" ]; then
+	echo " for target ${TARGET}" 
+else
+	echo ""
+fi
 
 echo "objdir = ${OBJDIR} / srcdir = ${SRCDIR}"
 
@@ -182,8 +199,8 @@ LIB_CHECK=""
 
 # Check for pkg-config (mandatory)
 
-echo -n "Checking for pkg-config ... "
-if [[ ! -x "$(which "${PKG_CONFIG}")" ]]; then
+printf "Checking for pkg-config ... "
+if ! env -i "PATH=${PATH}" command -v "${PKG_CONFIG}" >/dev/null 2>&1; then
 	fail "Error: PKG_CONFIG not valid"
 fi
 
@@ -193,58 +210,54 @@ which "${PKG_CONFIG}"
 # Support functions
 
 check_pkg() 
-{
-	echo -n "Checking for $1 ... "
+(
+	printf "Checking for %s ... " "$1"
 	"${PKG_CONFIG}" --exists "${1}"
-	local RT=$?
-	ok ${RT}
-	return ${RT}
-}
-
-fail()
-{
-	echo "${1}"
-	exit 1
-}
+	RT="$?"
+	ok "${RT}"
+	return "${RT}"
+)
 
 check_header()
-{
-	echo -n "Checking for ${1} ... "
+(
+	printf "Checking for %s ... " "$1"
 	# shellcheck disable=SC2086
 	echo "#include <${1}>" | \
 		${CC} ${CFLAGS} ${CPPFLAGS} ${LDFLAGS} -E - -o /dev/null 2>>config.log
-	local RT=$?
-	ok $?
-	return ${RT}
-}
+	RT="$?"
+	ok "${RT}"
+	return "${RT}"
+)
 
 check_lib()
-{
-	local F=/tmp/$$.c
+(
+	F="/tmp/$$.c"
 
 	echo "#define _XOPEN_SOURCE 700" >${F}
 	echo 'main(){}' >>${F}
-	echo -n "Checking for -l${1} ... "
+	printf "Checking for -l%s ... " "$1"
 	# shellcheck disable=SC2086
 	${CC} ${LDFLAGS} ${CPPFLAGS} ${CFLAGS} "-l${1}" ${F} \
 		-o /dev/null 2>>config.log
-	local RT=$?
-	ok ${RT}
-	rm -f ${F}
-	return ${RT}
-}
+	RT="$?"
+	ok "${RT}"
+	rm -f "${F}"
+	return "${RT}"
+)
 
 ok()
 {
-	[[ $1 -eq 0 ]] && echo "ok" ||  echo "not found"
+	if [ "$1" = 0 ]; then
+		echo "ok"
+	else 
+		echo "not found"
+	fi
 }
 
 check_func()
-{
-	local F=/tmp/$$.c
-	local FUNC
+(
+	F=/tmp/$$.c
 	FUNC="$(echo "${1}" | cut -d: -f1)"
-	local ARGS
 	ARGS="$(echo "${1}" | cut -d: -f2-)"
 
 	echo "#define _GNU_SOURCE" >${F}
@@ -252,18 +265,18 @@ check_func()
 		echo "#include <${i}>" >>${F}
 	done
 	echo "void main() { ${FUNC}(${ARGS}); }" >>${F}
-	echo -n "Checking for ${FUNC}() ... "
+	printf "Checking for %s() ... " "${FUNC}"
 	# shellcheck disable=SC2086
 	${CC} ${LDFLAGS} ${CPPFLAGS} ${CFLAGS} ${F} -o /dev/null 2>>config.log
-	local RT=$?
+	RT="$?"
 
-	ok ${RT}
-	rm -f ${F}
-	return ${RT}
-}
+	ok "${RT}"
+	rm -f "${F}"
+	return "${RT}"
+)
 
 # start a new configuration file
-if [[ -e ${OBJDIR}/config.h ]]; then 
+if [ -e "${OBJDIR}/config.h" ]; then 
 	mv -f "${OBJDIR}/config.h" "${OBJDIR}/config.h~"
 fi
 rm -f "${OBJDIR}/config.h"
